### ISSUE TITLE
Missing domain field in the URL

### ISSUE THREAD

**Issue by burak-create** [vippsas/backstage-azure-resources-backend#3]
Hi.

Am I missing something or is there a way to define the domain name in the configuration property?

I really appreciate any help you can provide :)

# Expected behavior
Reaching the listed resources via UI with the URL formatted like this;
`https://portal.azure.com/#@sample.domain/resource/subscriptions/0000-0000-0000-0000-0000/resourceGroups/rg-sample`

# Actual behavior
Getting ERR_INVALID_RESPONSE because of the link format;
`https://portal.azure.com/resource/subscriptions/0000-0000-0000-0000-0000/resourceGroups/rg-sample`

My configuration looks like this:
```
azureResources:
  clientId: ${AZURE_CLIENT_ID}
  clientSecret: ${AZURE_CLIENT_SECRET}
  tenantId: ${AZURE_TENANT_ID}
```

**Comment by ehrnst** [comment]
sorry for my late answer here. but where do you see this error? is the plugin failing to pull data from azure, or?

**Comment by burak-create** [comment]
No worries!

There is no problem with pulling the data. The only problem that I experienced so far is navigating to the azure portal.
It is supposed to navigate to the azure portal when you click the resource name under the resource groups field.

<img width="763" alt="Screenshot 2023-02-14 at 20 33 06" src="https://user-images.githubusercontent.com/70510104/218840237-f7c056ad-c840-4c97-8624-9bfe7a9b48da.png">

But you get _This site can’t be reached_ instead. Cuz there is no way to add the domain name.

`https://portal.azure.com/#@sample.domain/resource/subscriptions/0000-0000-0000-0000-0000/resourceGroups/rg-sample`

I guess the backend config could be something like this:

```
azureResources:
  domain:your.domain
  clientId: ab77a497-102e-4c4d-9853-3aca7e733245 # the app registrations clientId
  clientSecret: ~AcbyiAM2YUMQwUSqhzg # a secret created for the app registration
  tenantId: f02ae3d3-be5c-4b9d-9d6e-8192055d4083 # your Azure tenant id
```

And then maybe it's possible to reformat the link?

Sorry if it became a bit confusing for you. I'm quite new at this :D
